/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatusRouteImport } from './routes/status'
import { Route as PatientRouteImport } from './routes/patient'
import { Route as HospitalRouteImport } from './routes/hospital'
import { Route as GovRouteImport } from './routes/gov'
import { Route as ClinicRouteImport } from './routes/clinic'
import { Route as AppealRouteImport } from './routes/appeal'
import { Route as IndexRouteImport } from './routes/index'

const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientRoute = PatientRouteImport.update({
  id: '/patient',
  path: '/patient',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalRoute = HospitalRouteImport.update({
  id: '/hospital',
  path: '/hospital',
  getParentRoute: () => rootRouteImport,
} as any)
const GovRoute = GovRouteImport.update({
  id: '/gov',
  path: '/gov',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicRoute = ClinicRouteImport.update({
  id: '/clinic',
  path: '/clinic',
  getParentRoute: () => rootRouteImport,
} as any)
const AppealRoute = AppealRouteImport.update({
  id: '/appeal',
  path: '/appeal',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/appeal': typeof AppealRoute
  '/clinic': typeof ClinicRoute
  '/gov': typeof GovRoute
  '/hospital': typeof HospitalRoute
  '/patient': typeof PatientRoute
  '/status': typeof StatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/appeal': typeof AppealRoute
  '/clinic': typeof ClinicRoute
  '/gov': typeof GovRoute
  '/hospital': typeof HospitalRoute
  '/patient': typeof PatientRoute
  '/status': typeof StatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/appeal': typeof AppealRoute
  '/clinic': typeof ClinicRoute
  '/gov': typeof GovRoute
  '/hospital': typeof HospitalRoute
  '/patient': typeof PatientRoute
  '/status': typeof StatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/appeal'
    | '/clinic'
    | '/gov'
    | '/hospital'
    | '/patient'
    | '/status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/appeal'
    | '/clinic'
    | '/gov'
    | '/hospital'
    | '/patient'
    | '/status'
  id:
    | '__root__'
    | '/'
    | '/appeal'
    | '/clinic'
    | '/gov'
    | '/hospital'
    | '/patient'
    | '/status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppealRoute: typeof AppealRoute
  ClinicRoute: typeof ClinicRoute
  GovRoute: typeof GovRoute
  HospitalRoute: typeof HospitalRoute
  PatientRoute: typeof PatientRoute
  StatusRoute: typeof StatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient': {
      id: '/patient'
      path: '/patient'
      fullPath: '/patient'
      preLoaderRoute: typeof PatientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospital': {
      id: '/hospital'
      path: '/hospital'
      fullPath: '/hospital'
      preLoaderRoute: typeof HospitalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gov': {
      id: '/gov'
      path: '/gov'
      fullPath: '/gov'
      preLoaderRoute: typeof GovRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinic': {
      id: '/clinic'
      path: '/clinic'
      fullPath: '/clinic'
      preLoaderRoute: typeof ClinicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appeal': {
      id: '/appeal'
      path: '/appeal'
      fullPath: '/appeal'
      preLoaderRoute: typeof AppealRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppealRoute: AppealRoute,
  ClinicRoute: ClinicRoute,
  GovRoute: GovRoute,
  HospitalRoute: HospitalRoute,
  PatientRoute: PatientRoute,
  StatusRoute: StatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
